### PR TITLE
DRAFT: Routing notebooks

### PR DESCRIPTION
**Pull request by Willem-de-kok**
Adding a COMPLETED and an EMPTY notebook for routing.

Currently, there is still a bug coming from Stablebaselines @S-Linde do you know how to fix that?

### CODE REVIEW

**Comment by jhenstra** [comment]
@Willem-de-kok do you mean the "library is not initialised" bug when the check_env is done? I think that one is due to the env being rendered during reset.

**Comment by Willem-de-kok** [comment]
> @Willem-de-kok do you mean the "library is not initialised" bug when the check_env is done? I think that one is due to the env being rendered during reset.

Yes, I mean that bug. I don't understand how to work around it. Do you know?

**Comment by jhenstra** [comment]
> > @Willem-de-kok do you mean the "library is not initialised" bug when the check_env is done? I think that one is due to the env being rendered during reset.
> 
> 
> 
> Yes, I mean that bug. I don't understand how to work around it. Do you know?

When removing rendering from the reset method the bug should be gone. Rendering is something which should be done by the training or inference process. As the environment which is checked has a render mode set to 'human' it will try to render the environment during reset.

**Comment by S-Linde** [comment]
> > > @Willem-de-kok do you mean the "library is not initialised" bug when the check_env is done? I think that one is due to the env being rendered during reset.
> > 
> > 
> > Yes, I mean that bug. I don't understand how to work around it. Do you know?
> 
> When removing rendering from the reset method the bug should be gone. Rendering is something which should be done by the training or inference process. As the environment which is checked has a render mode set to 'human' it will try to render the environment during reset.

The problem is indeed caused by the render mode. The render mode should not be set to "human" during training, instead it should be `None` or `"rgb_array"`.

**Review by S-Linde — DISMISSED** [review]

**Review by S-Linde — APPROVED** [review]

**Pull request merged**
